<?php

/**
 * @file
 * Contains custom_drush_command.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_drush_command_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_drush_command module.
    case 'help.page.custom_drush_command':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Drush commmands as needed') . '</p>';
      return $output;

    default:
  }
}
